on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
    - name: Install Node.js
      uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c
      with:
        node-version: 24.11.1
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
