on:
  # Run on PRs and pushes to the default branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
      with:
        persist-credentials: false
    - name: Install Node.js
      uses: actions/setup-node@e51e5fe84fc33b4c73ebe40526b2694712b5b858
      with:
        node-version: 24.11.1
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
